\hypertarget{structPyOSErrorObject}{}\section{Py\+O\+S\+Error\+Object Struct Reference}
\label{structPyOSErrorObject}\index{Py\+O\+S\+Error\+Object@{Py\+O\+S\+Error\+Object}}
\subsection*{Public Attributes}
\begin{DoxyCompactItemize}
\item 
Py\+Exception\+\_\+\+H\+E\+AD \hyperlink{struct__object}{Py\+Object} $\ast$ {\bfseries myerrno}\hypertarget{structPyOSErrorObject_a7eeb951070c417b3eb579833b3495f34}{}\label{structPyOSErrorObject_a7eeb951070c417b3eb579833b3495f34}

\item 
\hyperlink{struct__object}{Py\+Object} $\ast$ {\bfseries strerror}\hypertarget{structPyOSErrorObject_ac678d65d807c599fd0f2a541372006cc}{}\label{structPyOSErrorObject_ac678d65d807c599fd0f2a541372006cc}

\item 
\hyperlink{struct__object}{Py\+Object} $\ast$ {\bfseries filename}\hypertarget{structPyOSErrorObject_ab50f77f250da6f83be31d21b55d0ef1a}{}\label{structPyOSErrorObject_ab50f77f250da6f83be31d21b55d0ef1a}

\item 
\hyperlink{struct__object}{Py\+Object} $\ast$ {\bfseries filename2}\hypertarget{structPyOSErrorObject_a8cd567c34bd9165a42f138f65399e066}{}\label{structPyOSErrorObject_a8cd567c34bd9165a42f138f65399e066}

\item 
Py\+\_\+ssize\+\_\+t {\bfseries written}\hypertarget{structPyOSErrorObject_a4e9f1f9a6361d9c56b8b71364c020055}{}\label{structPyOSErrorObject_a4e9f1f9a6361d9c56b8b71364c020055}

\end{DoxyCompactItemize}


\subsection{Detailed Description}


Definition at line 51 of file pyerrors.\+h.



The documentation for this struct was generated from the following file\+:\begin{DoxyCompactItemize}
\item 
/usr/include/python3.\+5m/pyerrors.\+h\end{DoxyCompactItemize}
