\hypertarget{structPySyntaxErrorObject}{}\section{Py\+Syntax\+Error\+Object Struct Reference}
\label{structPySyntaxErrorObject}\index{Py\+Syntax\+Error\+Object@{Py\+Syntax\+Error\+Object}}
\subsection*{Public Attributes}
\begin{DoxyCompactItemize}
\item 
Py\+Exception\+\_\+\+H\+E\+AD \hyperlink{struct__object}{Py\+Object} $\ast$ {\bfseries msg}\hypertarget{structPySyntaxErrorObject_a71896ef95d204cabfffbc25c44338a43}{}\label{structPySyntaxErrorObject_a71896ef95d204cabfffbc25c44338a43}

\item 
\hyperlink{struct__object}{Py\+Object} $\ast$ {\bfseries filename}\hypertarget{structPySyntaxErrorObject_aed7ca919fca31f79cda28d1cb0d62755}{}\label{structPySyntaxErrorObject_aed7ca919fca31f79cda28d1cb0d62755}

\item 
\hyperlink{struct__object}{Py\+Object} $\ast$ {\bfseries lineno}\hypertarget{structPySyntaxErrorObject_a518424d9f51fde459c23101d19e49c85}{}\label{structPySyntaxErrorObject_a518424d9f51fde459c23101d19e49c85}

\item 
\hyperlink{struct__object}{Py\+Object} $\ast$ {\bfseries offset}\hypertarget{structPySyntaxErrorObject_a0cb77b0acc909058c6c74cfdaa1ffdda}{}\label{structPySyntaxErrorObject_a0cb77b0acc909058c6c74cfdaa1ffdda}

\item 
\hyperlink{struct__object}{Py\+Object} $\ast$ {\bfseries text}\hypertarget{structPySyntaxErrorObject_aebd47dd29210b4107549874ee2253ede}{}\label{structPySyntaxErrorObject_aebd47dd29210b4107549874ee2253ede}

\item 
\hyperlink{struct__object}{Py\+Object} $\ast$ {\bfseries print\+\_\+file\+\_\+and\+\_\+line}\hypertarget{structPySyntaxErrorObject_a2680fe45d034e0d79c6395787b0186dd}{}\label{structPySyntaxErrorObject_a2680fe45d034e0d79c6395787b0186dd}

\end{DoxyCompactItemize}


\subsection{Detailed Description}


Definition at line 20 of file pyerrors.\+h.



The documentation for this struct was generated from the following file\+:\begin{DoxyCompactItemize}
\item 
/usr/include/python3.\+5m/pyerrors.\+h\end{DoxyCompactItemize}
